const std = @import("std");
const builtin = std.builtin;

pub fn genEnum(comptime id_strings: []const []const u8) type {
    var enum_fields: [id_strings.len]builtin.Type.EnumField = undefined;

    for (id_strings) |str, i| {
        enum_fields[i] = .{ .name = str, .value = i };
    }

    return @Type(builtin.Type{
        .Enum = .{
            .layout = .Auto,
            .tag_type = usize,
            .fields = &enum_fields,
            .is_exhaustive = true,
            .decls = &.{},
        },
    });
}

pub const packet_enum = genEnum(packet_ids[0..]);

pub const login_packet_enum = genEnum(Login_ids[0..]);

pub const Login_ids = [_][]const u8{
    "Disconnect",
    "Encryption_Request",
    "Login_Success",
    "Set_Compression",
    "Login_Plugin_Request",
};

pub const packet_ids = [_][]const u8{
    "Spawn_Entity",
    "Spawn_Experience_Orb",
    "Spawn_Player",
    "Entity_Animation",
    "Award_Statistics",
    "Acknowledge_Block_Change",
    "Set_Block_Destroy_Stage",
    "Block_Entity_Data",
    "Block_Action",
    "Block_Update",
    "Boss_Bar",
    "Change_Difficulty",
    "Clear_Titles",
    "Command_Suggestions_Response",
    "Commands",
    "Close_Container",
    "Set_Container_Content",
    "Set_Container_Property",
    "Set_Container_Slot",
    "Set_Cooldown",
    "Chat_Suggestions",
    "Plugin_Message",
    "Delete_Message",
    "Disconnect",
    "Disguised_Chat_Message",
    "Entity_Event",
    "Explosion",
    "Unload_Chunk",
    "Game_Event",
    "Open_Horse_Screen",
    "Initialize_World_Border",
    "Keep_Alive",
    "Chunk_Data_and_Update_Light",
    "World_Event",
    "Particle_2",
    "Update_Light",
    "Login",
    "Map_Data",
    "Merchant_Offers",
    "Update_Entity_Position",
    "Update_Entity_Position_and_Rotation",
    "Update_Entity_Rotation",
    "Move_Vehicle",
    "Open_Book",
    "Open_Screen",
    "Open_Sign_Editor",
    "Ping",
    "Place_Ghost_Recipe",
    "Player_Abilities",
    "Player_Chat_Message",
    "End_Combat",
    "Enter_Combat",
    "Combat_Death",
    "Player_Info_Remove",
    "Player_Info_Update",
    "Look_At",
    "Synchronize_Player_Position",
    "Update_Recipe_Book",
    "Remove_Entities",
    "Remove_Entity_Effect",
    "Resource_Pack",
    "Respawn",
    "Set_Head_Rotation",
    "Update_Section_Blocks",
    "Select_Advancements_Tab",
    "Server_Data",
    "Set_Action_Bar_Text",
    "Set_Border_Center",
    "Set_Border_Lerp_Size",
    "Set_Border_Size",
    "Set_Border_Warning_Delay",
    "Set_Border_Warning_Distance",
    "Set_Camera",
    "Set_Held_Item",
    "Set_Center_Chunk",
    "Set_Render_Distance",
    "Set_Default_Spawn_Position",
    "Display_Objective",
    "Set_Entity_Metadata",
    "Link_Entities",
    "Set_Entity_Velocity",
    "Set_Equipment",
    "Set_Experience",
    "Set_Health",
    "Update_Objectives",
    "Set_Passengers",
    "Update_Teams",
    "Update_Score",
    "Set_Simulation_Distance",
    "Set_Subtitle_Text",
    "Update_Time",
    "Set_Title_Text",
    "Set_Title_Animation_Times",
    "Entity_Sound_Effect",
    "Sound_Effect",
    "Stop_Sound",
    "System_Chat_Message",
    "Set_Tab_List_Header_And_Footer",
    "Tag_Query_Response",
    "Pickup_Item",
    "Teleport_Entity",
    "Update_Advancements",
    "Update_Attributes",
    "Feature_Flags",
    "Entity_Effect",
    "Update_Recipes",
    "Update_Tags",
};

pub const ServerBoundPlayIds = [_][]const u8{
    "Confirm_Teleportation",
    "Query_Block_Entity_Tag",
    "Change_Difficulty_2",
    "Message_Acknowledgment",
    "Chat_Command",
    "Chat_Message",
    "Client_Command",
    "Client_Information",
    "Command_Suggestions_Request",
    "Click_Container_Button",
    "Click_Container",
    "Close_Container_2",
    "Plugin_Message_2",
    "Edit_Book",
    "Query_Entity_Tag",
    "Interact",
    "Jigsaw_Generate",
    "Keep_Alive_2",
    "Lock_Difficulty",
    "Set_Player_Position",
    "Set_Player_Position_and_Rotation",
    "Set_Player_Rotation",
    "Set_Player_On_Ground",
    "Move_Vehicle_2",
    "Paddle_Boat",
    "Pick_Item",
    "Place_Recipe",
    "Player_Abilities_2",
    "Player_Action",
    "Player_Command",
    "Player_Input",
    "Pong",
    "Player_Session",
    "Change_Recipe_Book_Settings",
    "Set_Seen_Recipe",
    "Rename_Item",
    "Resource_Pack_2",
    "Seen_Advancements",
    "Select_Trade",
    "Set_Beacon_Effect",
    "Set_Held_Item_2",
    "Program_Command_Block",
    "Program_Command_Block_Minecart",
    "Set_Creative_Mode_Slot",
    "Program_Jigsaw_Block",
    "Program_Structure_Block",
    "Update_Sign",
    "Swing_Arm",
    "Teleport_To_Entity",
    "Use_Item_On",
    "Use_Item",
};
